import { uniqueId } from "lodash";

import {
  IconAperture,
  IconCopy,
  IconLayoutDashboard,
  IconLogin,
  IconMoodHappy,
  IconTypography,
  IconUserPlus,
  IconPackage,
  IconUsers,
  IconTrendingUp,
  IconCategory,
  IconEye,
  IconPlus,
  IconAlertTriangle,
  IconShoppingCart,
  IconStar,
  IconFileText,
  IconSettings,
  IconChartBar,
  IconDownload,
  IconUpload,
  IconHistory,
  IconUser,
  IconShield,
  IconCash,
  IconWorld,
  IconHome,
  IconReceipt,
  IconPercentage,
  IconChartLine,
  IconPoint,
  IconClipboardList,
  IconTags,
  IconCurrencyDollar,
  IconTruck,
  IconEdit,
  IconFilter,
  IconDatabase,
  IconBell,
  IconLogout,
  IconChartPie,
  IconReportAnalytics,
  IconBoxSeam,
  IconShoppingBag,
  IconDiscount2,
  IconCalendarEvent,
  IconFileInvoice,
} from "@tabler/icons-react";
import { NavGroup } from "@/app/types/layout/sidebar";

const MudrasMenuItems: NavGroup[] = [
  {
    navlabel: true,
    subheader: "Inicio",
  },
  {
    id: uniqueId(),
    title: "Inicio",
    icon: IconHome,
    href: "/panel",
    requiredPermission: "dashboard:read",
  },

  {
    navlabel: true,
    subheader: "Gestión de Inventario",
  },
  {
    id: uniqueId(),
    title: "Artículos",
    icon: IconPackage,
    href: "/panel/articulos",
    requiredPermission: "productos:read",
  },
  {
    id: uniqueId(),
    title: "Proveedores",
    icon: IconUsers,
    href: "/panel/proveedores",
    requiredPermission: "proveedores:read",
  },
  {
    id: uniqueId(),
    title: "Puntos de Venta",
    icon: IconShoppingBag,
    href: "/panel/puntos-venta",
    requiredPermission: "puntos_venta:read",
  },
  {
    id: uniqueId(),
    title: "Depósitos",
    icon: IconBoxSeam,
    href: "/panel/depositos",
    requiredPermission: "depositos:read",
  },
  {
    id: uniqueId(),
    title: "Asignación Global",
    icon: IconChartPie,
    href: "/panel/stock/asignacion-global",
    requiredPermission: "stock:update",
  },

  {
    navlabel: true,
    subheader: "Ventas y Comercial",
  },
  {
    id: uniqueId(),
    title: "Caja",
    icon: IconCash,
    href: "/panel/ventas/caja",
    requiredPermission: "caja:read",
  },
  {
    id: uniqueId(),
    title: "Ventas",
    icon: IconShoppingCart,
    href: "/panel/ventas",
    requiredPermission: "ventas:read",
  },
  {
    id: uniqueId(),
    title: "Tienda Online",
    icon: IconWorld,
    href: "/panel/tienda",
    requiredPermission: "tienda_online:read",
  },
  {
    id: uniqueId(),
    title: "Promociones",
    icon: IconStar,
    href: "/panel/promociones",
    requiredPermission: "promociones:read",
  },
  {
    id: uniqueId(),
    title: "Pedidos",
    icon: IconReceipt,
    href: "/panel/pedidos",
    requiredPermission: "pedidos:read",
  },

  {
    navlabel: true,
    subheader: "Administración",
  },
  {
    id: uniqueId(),
    title: "Usuarios",
    icon: IconUser,
    href: "/panel/usuarios",
    requiredPermission: "usuarios:read",
  },
  {
    id: uniqueId(),
    title: "Puntos Mudras",
    icon: IconBoxSeam,
    href: "/panel/puntos-mudras",
    requiredPermission: "puntos_mudras:read",
  },
];

export default MudrasMenuItems;
